### ISSUE TITLE
quick fixes after user testing

### ISSUE THREAD

**Issue by meganrm** [simularium/binding-sim-edu#119]
## Fixes 

- [x] typo on page 8 (switch A and B) 
- [x] add the definition of Kd on page 8 
- [x] fix final three titles 
- [x] fix wording on kd quiz question 
- [x] make definitions show on hover and underlined
- [ ] #149
- [x] clearer wording on page 7 (has been updated in the design)
- [x] move play button 
- [x] make icon on play button bigger 
- [x] add units and the word "approximate" to Kd quiz question 
- [x] change style of record button
- ~~show a next button each time they successfully record a point~~

**Comment by lynwilhelm** [comment]
Wow, you are fast @meganrm! I was editing above to add these few items:

- [ ] typo on page 8 (switch A and B) 
- [ ] add the definition of Kd on page 8 (**Lyndsay: on both pages 7 and 8**)
- [ ] fix final three titles 
- [ ] fix wording on kd quiz question **(Lyndsay: Also add unit uM)**
- [ ] make definitions on hover **(Lyndsay: add underline on hover and when popup is active)**
- [ ] add camera controls to viewer 
- [ ] clearer wording on page 7

**Comment by lynwilhelm** [comment]
This is a very fast idea...feel free to tweak if you can expand on this. I didn't like that we were asking the same question twice on two different lines.

![Screenshot 2024-09-30 at 4 37 51 PM](https://github.com/user-attachments/assets/2321288b-b654-473c-83c7-8a79877deee0)

**Comment by meganrm** [comment]
the bold wording should be "You have now measured enough points to estimate the value of B where half of the binding sites of A are occupied." which is on panel 8
